plugins {
    id "net.neoforged.moddev" version "2.0.140"
}

repositories {
    mavenCentral()
    maven { url = "https://maven.neoforged.net/releases" }
}

dependencies {
    implementation project(":common")
}

neoForge {
    version = "21.1.218"
    validateAccessTransformers = true

    runs {
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }

    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }
}