#----------------------------------------------------------------
# __   __  _____    _        _   _
# \ \ / / |  __ \  | |      (_) | |
#  \ V /  | |  | | | |       _  | |__
#   > <   | |  | | | |      | | | '_ \
#  / . \  | |__| | | |____  | | | |_) |
# /_/ \_\ |_____/  |______| |_| |_.__/
#
#----------------------------------------------------------------
# Enables the plugin
enabled: true
#
# Shows a welcome message to new players
welcomeMessage: true
#
# Adds custom join and leave messages
customJoinMessages: true
#
# Changed the message looks
customChatMessages: true
#
# Enables the TPA command for any player to run
tpaCommand: true
#----------------------------------------------------------------