modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/XDPXI/XDLib/issues"
license = "Apache 2.0"

[[mods]]
modId = "xdlib"
version = "${version}"
displayName = "XD's Library"
authors = "XDPXI"
description = '''
This is a library for many uses and is included as an player counter for XDPXI's mods and modpacks!
'''
#logoFile = ""

[[dependencies.xdlib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xdlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "xdlib.mixins.json"
