plugins {
    id "net.neoforged.moddev" version "2.0.143"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

dependencies {
    implementation project(":common")

    jarJar("org.yaml:snakeyaml:2.6")
}

neoForge {
    version = "26.1.2.94"
    validateAccessTransformers = true

    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }
}
